spring:
  application:
    name: Microservice-1
#For Admin-client 
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:1111/
#For Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
#For Zipkin
  tracing:
    sampling:
      probability: 0.1

#Eureka
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      
