server:
  port: 9095
spring:
  application:
    name: Microservice-2
#For Admin-client 
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:1111/
        
#For Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

#Eureka
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka